FROM alpine:3.6

RUN apk add --no-cache \
        bash \
        ca-certificates \
        coreutils \
        curl \
        gettext \
        git \
        wget \
    && rm -f /var/cache/apk/*

ENV YAML_BIN_VERSION 1.11
ENV JQ_BIN_VERSION 1.5

RUN wget -O /usr/local/bin/jq "https://github.com/stedolan/jq/releases/download/jq-${JQ_BIN_VERSION}/jq-linux64" \
    && chmod 755 /usr/local/bin/jq \
    && wget -O /usr/local/bin/yaml "https://github.com/mikefarah/yaml/releases/download/${YAML_BIN_VERSION}/yaml_linux_amd64" \
    && chmod 755 /usr/local/bin/yaml

ARG DEVELOPER

RUN git config --global user.name "${DEVELOPER}" \
    && git config --global user.email "${DEVELOPER}@gmail.com" \
    && git config --list
